### ISSUE TITLE
Vimeo download does not work

### ISSUE THREAD

**Issue by geopet85** [axet/vget#32]
It seems that Vimeo download does not work any more. When I try to download any Vimeo video, i get the following exception:

> com.github.axet.wget.info.ex.DownloadError: unknown config vimeo respond
> at com.github.axet.vget.vhs.VimeoParser.extractLinks(VimeoParser.java:159)
> at com.github.axet.vget.vhs.VimeoParser.extract(VimeoParser.java:208)
> ...

Is this valid?

**Comment by geopet85** [comment]
It appears that Vimeo have changed all their links to HTTPS, and that was not expected by some parts of the code. 

If you change line 129 of VimeoParser.java to:

> clip = "https://vimeo.com/" + id;

the issue should be solved.
