### ISSUE TITLE
Unable to extract the helper decode functions!

### ISSUE THREAD

**Issue by BillyHalley** [axet/vget#61]
I just copied the simple example into a new project in eclips, imported vget project and when I run i get this:
```
Exception in thread "main" java.lang.RuntimeException: com.github.axet.wget.info.ex.DownloadError: Unable to extract the helper decode functions!
	at DirectDownload.main(DirectDownload.java:18)
Caused by: com.github.axet.wget.info.ex.DownloadError: Unable to extract the helper decode functions!
	at com.github.axet.vget.vhs.YouTubeParser$DecryptSignatureHtml5.extractDecodeFunctions(YouTubeParser.java:261)
	at com.github.axet.vget.vhs.YouTubeParser$DecryptSignatureHtml5.decrypt(YouTubeParser.java:280)
	at com.github.axet.vget.vhs.YouTubeParser.extractUrlEncodedVideos(YouTubeParser.java:819)
	at com.github.axet.vget.vhs.YouTubeParser.extractEmbedded(YouTubeParser.java:589)
	at com.github.axet.vget.vhs.YouTubeParser.extractLinks(YouTubeParser.java:365)
	at com.github.axet.vget.vhs.YouTubeParser.extract(YouTubeParser.java:840)
	at com.github.axet.vget.info.VGetParser.info(VGetParser.java:17)
	at com.github.axet.vget.VGet.extract(VGet.java:405)
	at com.github.axet.vget.VGet.download(VGet.java:487)
	at com.github.axet.vget.VGet.download(VGet.java:96)
	at DirectDownload.main(DirectDownload.java:16)
```

What am I missing?

**Comment by axet** [comment]
It seems you use bad http://youtube.com url

**Comment by BillyHalley** [comment]
I tried with the url provided in the example:
http://www.youtube.com/watch?v=Nj6PFaDmp6c

**Comment by axet** [comment]
Working fine on my machine. Maybe your's firewalled?
