### ISSUE TITLE
Unable to extract the main decode function

### ISSUE THREAD

**Issue by comdude2** [axet/vget#68]
`ERROR: Unable to extract the main decode function! CAUSE: null
com.github.axet.wget.info.ex.DownloadError: Unable to extract the main decode function!
	at com.github.axet.vget.vhs.YouTubeParser$DecryptSignatureHtml5.extractDecodeFunctions(YouTubeParser.java:244)
	at com.github.axet.vget.vhs.YouTubeParser$DecryptSignatureHtml5.decrypt(YouTubeParser.java:280)
	at com.github.axet.vget.vhs.YouTubeParser.extractUrlEncodedVideos(YouTubeParser.java:819)
	at com.github.axet.vget.vhs.YouTubeParser.extractEmbedded(YouTubeParser.java:589)
	at com.github.axet.vget.vhs.YouTubeParser.extractLinks(YouTubeParser.java:365)
	at com.github.axet.vget.vhs.YouTubeParser.extract(YouTubeParser.java:840)
	at com.github.axet.vget.info.VGetParser.info(VGetParser.java:17)
	at com.github.axet.vget.VGet.extract(VGet.java:405)
	at com.github.axet.vget.VGet.download(VGet.java:487)
	at com.github.axet.vget.VGet.download(VGet.java:96)
	at net.comdude2.apps.pcmanager.music.MusicDownloader.run(MusicDownloader.java:172)
	at java.lang.Thread.run(Unknown Source)`

The url i am using is: "https://www.youtube.com/watch?v=NqmjBSurfWY"

Using maven to get the library and using the direct download code with the above url, tried disabling firewall too, to no avail.

**Comment by deprilula28** [comment]
I'm also getting this issue :\

**Comment by deprilula28** [comment]
Update: It works after using my VPN that fakes I'm in the USA so it's definetely the protocol. Trying seeing if it works for you too

**Comment by comdude2** [comment]
Hmm, it starts downloading when using a VPN to fake location as you suggested, I then get another Exception to do system can't find the path specified, It might be the file destination. Either way, the lib needs to get it fixed so that a VPN is not required.

**Comment by axet** [comment]
Read the following guys:

https://github.com/axet/vget/blob/master/docs/YouTube.md

**Comment by comdude2** [comment]
So should we be doing something like:

VideoInfo.getSource(); after passing it with the VGetParser and then download from the source URL with the wget lib?

**Comment by axet** [comment]
It saying you need to debug the library and find out why encryption can not be decrypted.

**Comment by comdude2** [comment]
Well I guess I won't be using the lib then

**Comment by deprilula28** [comment]
axet After that, I fix it and send it as a pull request to you?

**Comment by axet** [comment]
sure

**Comment by jabrena** [comment]
I have the sam problem.

> 
Exception in thread "main" com.github.axet.wget.info.ex.DownloadError: Unable to determine the name of the helper decode function!`
