### ISSUE TITLE
NullPointerException when no video shall be downloaded

### ISSUE THREAD

**Issue by nnscr** [axet/vget#71]
Hi and thanks for your lib,

I try to download only the audio stream from an YouTube video. In issue #60 @axet mentions to use filters to accomplish that. I tried that and got an NullPointerException. 

I guess that filter should look like this:
```java
    public class YouTubeAudioOnlyParser extends YouTubeParser {
        @Override
        public void filter(List<VideoDownload> sNextVideoURL, String itag, URL url) {
            int i = Integer.decode(itag);
            YouTubeInfo.StreamInfo vd = itagMap.get(i);

            if (!(vd instanceof YouTubeInfo.StreamAudio)) {
                return;
            }
            // Yes, this line is executed once at least...
            filter(sNextVideoURL, itag, url);
        }
    }
```

Call:
```java
VGet g = new VGet(
    new URL("..."),
    new File("...")
);

g.download(new YouTubeAudioOnlyParser());
```

But unfortunately that throws a NullPointerException at:
```
Exception in thread "main" java.lang.NullPointerException
	at com.github.axet.vget.info.VGetParser.info(VGetParser.java:21)
	at com.github.axet.vget.VGet.extract(VGet.java:415)
	at com.github.axet.vget.VGet.download(VGet.java:499)
	at com.github.axet.vget.VGet.download(VGet.java:109)
```

Am I missing something or is this a bug?

**Comment by axet** [comment]
1) it is a bug

2) it should be super.filter(...)

2) also you shouldn't do this since youtube may have no audio only streams (old videos coded as combined streams only)

vget-1.2.5
