### ISSUE TITLE
RuntimeException 

### ISSUE THREAD

**Issue by powerthazan** [axet/vget#72]
Project was compiled with Java 7. Some users getting this error

`Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

`Caused by java.lang.NoClassDefFoundError: javax.script.ScriptEngineManager
       at com.github.axet.vget.vhs.YouTubeParser$DecryptSignatureHtml5.decrypt(SourceFile:272)
       at com.github.axet.vget.vhs.YouTubeParser.extractUrlEncodedVideos(SourceFile:826)
       at com.github.axet.vget.vhs.YouTubeParser.extractHtmlInfo(SourceFile:673)
       at com.github.axet.vget.vhs.YouTubeParser.streamCapture(SourceFile:412)
       at com.github.axet.vget.vhs.YouTubeParser.extractLinks(SourceFile:360)
       at com.github.axet.vget.vhs.YouTubeParser.extract(SourceFile:846)
       at com.github.axet.vget.info.VGetParser.info(SourceFile:17)
       at com.github.axet.vget.VGet.extract(SourceFile:415)
       at com.github.axet.vget.VGet.extract(SourceFile:395)
       at com.github.axet.vget.VGet.extract(SourceFile:387)
       at com.myactivity.SearchActivity$3$1.doInBackground(SourceFile:194)
       at com.myactivity.SearchActivity$3$1.doInBackground(SourceFile:188)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

**Comment by axet** [comment]
android?

**Comment by powerthazan** [comment]
yes. On Android

**Comment by axet** [comment]
Android is not supported due to lack of javax.* packages.

**Comment by axet** [comment]
You can try it.

```gradle
    compile fileTree(dir: 'libs', include: ['jsr223.jar'])
    compile('com.github.axet:vget:1.2.4') {
        exclude group: 'com.thoughtworks.xstream', module: 'xstream'
    }
```

**Comment by powerthazan** [comment]
Compiled successfully and App released to beta test users. I'll update here with report

**Comment by powerthazan** [comment]
Compiled successfully and released to Beta testers. I'll update here report

**Comment by powerthazan** [comment]
Not working. `Caused by java.lang.NoClassDefFoundError: javax.script.ScriptEngineManager`
