### ISSUE TITLE
"Do not use setTarget file on multiply source download"

### ISSUE THREAD

**Issue by iAmGio** [axet/vget#73]
`com.github.axet.wget.info.ex.DownloadError: Do not use setTarget file on multiply source download
	at com.github.axet.vget.VGet.targetFileForce(VGet.java:291)
	at com.github.axet.vget.VGet.targetFile(VGet.java:356)
	at com.github.axet.vget.VGet.download(VGet.java:540)
	at com.github.axet.vget.VGet.download(VGet.java:101)
	at eu.iamgio.ytdownloader.Downloader.download(Downloader.java:33)
	at eu.iamgio.ytdownloader.YoutubeDownloader.main(YoutubeDownloader.java:34)`

Code:
`URL source = new URL(url);`
`VGetParser parser = VGet.parser(source);`
`VideoInfo info = parser.info(source);`
`VGet vGet = new VGet(info);`
`vGet.setTarget(new File(name));`
`vGet.download();`

**Comment by axet** [comment]
use set target dir instead

**Comment by iAmGio** [comment]
I need to specify the filename

**Comment by axet** [comment]
Then do it individually for every VideoInfo

**Comment by iAmGio** [comment]
info.getInfo() returns null.

**Comment by iAmGio** [comment]
Please reply.
